application: examiner
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.4"

handlers:

- url: /static/(.*)/(.+)\..+\.\d+\.(.*)
  static_files: static/\1/\2.\3
  upload: static/*.*
  expiration: '3650d'

- url: /static
  static_dir: static
  expiration: '3650d'

- url: /.*
  script: wsgi.application
